on: [workflow_dispatch]
jobs:
  postgres:
    runs-on: ubuntu-latest
    container: ubuntu:focal
    steps:
      - run: |
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main"
          sudo apt update
          sudo apt -y install postgresql-12 postgresql-client-12 postgresql-contrib-12 libpq-dev
          echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/12/main/pg_hba.conf
          sudo su -c psql postgres postgres << EOT
            CREATE ROLE okapi WITH PASSWORD 'okapi25' LOGIN CREATEDB;
            CREATE DATABASE okapi WITH OWNER okapi ENCODING 'UTF-8' LC_COLLATE 'und-x-icu' LC_CTYPE 'und-x-icu' TEMPLATE template0;
            CREATE ROLE folio WITH PASSWORD 'folio123' LOGIN SUPERUSER;
            CREATE DATABASE folio WITH OWNER folio ENCODING 'UTF-8' LC_COLLATE 'und-x-icu' LC_CTYPE 'und-x-icu' TEMPLATE template0;
            EOT
